DROP TABLE IF EXISTS cats;

CREATE TABLE cats (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    imageURL TEXT NOT NULL,
    imageDescription text not null,
    name text not null,
    sex text not null,
    age integer not null,
    breed text not null,
    story text not null,
    day_added timestamp DEFAULT now() not null,
    adopted text default 'false'
);